config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'biskit', to: 'biskits#biskit'
  get 'jenaijamais', to: 'nevers#jenaijamais'

  resources :prefereds do
    member do
      get :update_vote2
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :nevers, only: [:index]
      resources :prefereds, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jenaijamai.rb
class Jenaijamai < ApplicationRecord
end

app/models/never.rb
class Never < ApplicationRecord
end

app/models/prefered.rb
class Prefered < ApplicationRecord
      validates :text, presence: true, uniqueness: true
      validates :text2, presence: true, uniqueness: true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
end

app/controllers/api/v1/nevers_controller.rb
class Api::V1::NeversController < Api::V1::BaseController

  def index
    @questions = Never.all
  end
end

app/controllers/api/v1/prefereds_controller.rb
class Api::V1::PreferedsController < Api::V1::BaseController
  def index
    @questions = Prefered.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def default_url_options
    { host: ENV["HOST"] || "http://questcequonfaitpourlapero.fr" }
  end
end

app/controllers/biskits_controller.rb
class BiskitsController < ApplicationController
    def biskit
    end
end

app/controllers/nevers_controller.rb
class NeversController < ApplicationController
    def jenaijamais
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        time = Time.new
        if time.min > 10
            now = "#{time.hour}h#{time.min}"
        else
            now = "#{time.hour}h0#{time.min}"
        end

        if time.hour < 12
            @text = "Apéro à #{now} ? Vous êtes chaud !"
        elsif time.hour >= 12 && time.hour < 17
            @text = "L'apéro de #{now}, c'est le meilleur... Bon après-midi !"
        elsif time.hour >= 17 && time.hour < 23
            @text = "#{now}, l'heure parfaite pour l'apéro !"
        elsif time.hour >= 23 && time.hour < 8
            @text = "Je ne sais pas si on peut toujours appeler ça un Apéro à #{now} !"
        end
    end
end

app/controllers/prefereds_controller.rb
class PreferedsController < ApplicationController
    
    def index
        questions = Prefered.all
        @question = questions.sample 
        @vote1 = @question.vote1 + 1
        @vote2 = @question.vote2 + 1    

        pourcentage_vote_1
        pourcentage_vote_2
    end
    
    def show
        @question = Prefered.find(params[:id])
        vote1 = @question.vote1 + 1
        
        if @question.update(vote1: vote1)
            redirect_to prefereds_path
        end
    end

    def new
        @question = Prefered.new
    end

    def create
        @question = Prefered.create(question_params)
        redirect_to prefereds_path
    end

    
    def update_vote2
        @question = Prefered.find(params[:id])
        vote2 = @question.vote2 + 1
        if @question.update(vote2: vote2)
            redirect_to prefereds_path
        end
    end
    
    private 

    def question_params
        params.require(:prefered).permit(:text, :text2)
    end
    
    def pourcentage_vote_1
        total1 = @vote1 + @question.vote2
        @pourcent1 = (@vote1 * 100) / total1
    end
    
    def pourcentage_vote_2
        total2 = @vote2 + @question.vote1
        @pourcent2 = (@vote2 * 100) / total2
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biskits_helper.rb
module BiskitsHelper
end

app/helpers/jenaijamais_helper.rb
module JenaijamaisHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/nevers_helper.rb
module NeversHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prefereds_helper.rb
module PreferedsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/biskits/biskit.html.erb
<div class="wrapper-biskit">
    <div class="head">
        <span><%= link_to 'Retour', root_path %></span>
        <h1>Biskit</h1>
    </div>
    <div class="result">
        <div class="dices">
            <section class="container">
                <div id="cube1">
                    <figure class="front">1</figure>
                    <figure class="back">2</figure>
                    <figure class="right">3</figure>
                    <figure class="left">4</figure>
                    <figure class="top">5</figure>
                    <figure class="bottom">6</figure>
                </div>
            </section>
            <section class="container">
                <div id="cube2">
                    <figure class="front">1</figure>
                    <figure class="back">2</figure>
                    <figure class="right">3</figure>
                    <figure class="left">4</figure>
                    <figure class="top">5</figure>
                    <figure class="bottom">6</figure>
                </div>
            </section>
        </div>
        <div class="roll-dices">
            <div class="btn-roll">
                <p>Lancer les dés</p>
            </div>
        </div>

        <div id="action">
            <p>10</p>
        </div>
    </div>

    <content>
        <div class="rules">
            <div class="rules-list hidden">
                <ul>
                    <li>Si vous consultez les règles durant la partie, <strong>"Perte des notions du jeux"</strong>, vous buvez une gorgée.</li>
                    <li>Si la personne concernée par le tirage met plus de 10 secondes à réagir, <strong>"Perte des notions du jeux"</strong>, elle boit une gorgée.</li>
                    <li><strong>3</strong> : Vous devenez Le Biskit. Dès que le chiffre 3 apparait sur l'une des faces, vous buvez une gorgée.</li>
                    <li><strong>7</strong> : Criez biskit tout en mettant votre pouce sur votre front. La dernière personne à l'avoir fait boit une gorgée.</li>
                    <li><strong>9</strong> : La personne avant vous doit boire une gorgée.</li>
                    <li><strong>10</strong> : Vous buvez une gorgée.</li>
                    <li><strong>11</strong> : La personne après vous doit boire une gorgée.</li>
                    <li><strong>Doubles</strong> : Distribuez quatre gorgées si c'est un double 4, deux gorgées si c'est un double 2... Vous avez compris. </li>
                    <li><strong>Double 1</strong> : Tout le monde boit une gorgée !</li>
                    <li><strong>Double 6</strong> : Inventez une règle !</li>
                </ul>
            </div>
            <div class="rules-btn">
                <p><i class="fas fa-sort-down"></i> Afficher les règles <i class="fas fa-sort-down"></i></p>
                <span class="hidden"><i class="fas fa-sort-up"></i> Masquer les règles <i class="fas fa-sort-up"></i></span>
            </div>
        </div>
    </content>
</div>

app/views/nevers/jenaijamais.html.erb
<div class="wrapper-never">
    <div class="head">
        <span><%= link_to 'Retour', root_path %></span>
        <h1>Je n'ai jamais</h1>
    </div>
    <div class="question-wrapper">
        <div class="question-center">
            <div class="question">
            </div>

            <div class="next">
                <button>Suivant</button>
            </div>

            <div class="rappel">
                <p>Rappel : Si c'est le cas, vous buvez une gorgée.</p>
            </div>
        </div>
    </div>
</div>

app/views/prefereds/_question.html.erb
<div class="question1">
    <div id="vote1">
        <h1><%= @question.text %></h1>
    </div>
</div>
<div class="resultat1 red hidden">
    <div class="question_result">
        <p><%= @question.text %></p>
    </div>
    <div class="question_pourcent">
        <h2><%= @pourcent1 %> %</em></h2>
    </div>
    <div class="question_vote">
        <span><%= @vote1 %> votes</em></span>
    </div>
    <div class="question_next">
        <%= link_to "Suivant", prefered_path(@question.id) %>
    </div>
</div>

<div class="question2">
    <div id="vote2">
        <h1><%= @question.text2 %></h1>
    </div>
</div>
<div class="resultat2 red hidden">
    <div class="question_result">
        <p><%= @question.text2 %></p>
    </div>
    <div class="question_pourcent">
        <h2><%= @pourcent2 %> %</em></h2>
    </div>
    <div class="question_vote">
        <span><%= @vote2 %> votes</span>
    </div>
    <div class="question_next">
        <%= link_to "Suivant", update_vote2_prefered_path(@question.id) %>
    </div>
</div>

app/views/prefereds/index.html.erb
<div class="wrapper-preferes">
    <div class="head">
        <span><%= link_to 'Retour', root_path %></span>
        <h1>Tu préfères ?</h1>
    </div>
    <div class="preferes-question-wrapper">
        <%= render "question" %>
    </div>
    
</div>

app/views/prefereds/new.html.erb
<div class="wrapper-form">
    <div class="form">
        <%= simple_form_for @question do |f| %>
            <%= f.input :text, label: "Tu préfères :" %>
            <%= f.input :text2, label: "Ou :" %>
            <%= f.submit %>
        <% end %>
    </div>
</div>