config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'biskit', to: 'biskits#biskit'
  get 'jenaijamais', to: 'nevers#jenaijamais'

  resources :prefereds do
    member do
      get :update_vote2
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :nevers, only: [:index]
      resources :prefereds, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jenaijamai.rb
class Jenaijamai < ApplicationRecord
end

app/models/never.rb
class Never < ApplicationRecord
end

app/models/prefered.rb
class Prefered < ApplicationRecord
      validates :text, presence: true, uniqueness: true
      validates :text2, presence: true, uniqueness: true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
end

app/controllers/api/v1/nevers_controller.rb
class Api::V1::NeversController < Api::V1::BaseController

  def index
    @questions = Never.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def default_url_options
    { host: ENV["HOST"] || "http://questcequonfaitpourlapero.fr" }
  end
end

app/controllers/biskits_controller.rb
class BiskitsController < ApplicationController
    def biskit
    end
end

app/controllers/nevers_controller.rb
class NeversController < ApplicationController
    def jenaijamais
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        time = Time.new
        if time.min > 10
            now = "#{time.hour}h#{time.min}"
        else
            now = "#{time.hour}h0#{time.min}"
        end

        if time.hour < 12
            @text = "Apéro à #{now} ? Vous êtes chaud !"
        elsif time.hour >= 12 && time.hour < 17
            @text = "L'apéro de #{now}, c'est le meilleur... Bon après-midi !"
        elsif time.hour >= 17 && time.hour < 23
            @text = "#{now}, l'heure parfaite pour l'apéro !"
        elsif time.hour >= 23 && time.hour < 8
            @text = "Je ne sais pas si on peut toujours appeler ça un Apéro à #{now} !"
        end
    end
end

app/controllers/prefereds_controller.rb
class PreferedsController < ApplicationController
    
    def index
        questions = Prefered.all
        @question = questions.sample 
        @vote1 = @question.vote1 + 1
        @vote2 = @question.vote2 + 1    

        pourcentage_vote_1
        pourcentage_vote_2
    end
    
    def show
        @question = Prefered.find(params[:id])
        vote1 = @question.vote1 + 1
        
        if @question.update(vote1: vote1)
            redirect_to prefereds_path
        end
    end

    def new
        @question = Prefered.new
    end

    def create
        @question = Prefered.create(question_params)
        redirect_to prefereds_path
    end

    
    def update_vote2
        @question = Prefered.find(params[:id])
        vote2 = @question.vote2 + 1
        if @question.update(vote2: vote2)
            redirect_to prefereds_path
        end
    end
    
    private 

    def question_params
        params.require(:prefered).permit(:text, :text2)
    end
    
    def pourcentage_vote_1
        total1 = @vote1 + @question.vote2
        @pourcent1 = (@vote1 * 100) / total1
    end
    
    def pourcentage_vote_2
        total2 = @vote2 + @question.vote1
        @pourcent2 = (@vote2 * 100) / total2
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biskits_helper.rb
module BiskitsHelper
end

app/helpers/jenaijamais_helper.rb
module JenaijamaisHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/nevers_helper.rb
module NeversHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prefereds_helper.rb
module PreferedsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119897489-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-119897489-1');
    </script>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application' %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono|Oswald" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="wrapper-home">
    <header>
        <div class="header">
            <div class="title">
                <h1>
                    Qu'est ce qu'on fait pour l'apéro ?
                </h1>
            </div>
            <div class="time">
                <span><%= @text %></span>
            </div>
        </div>
    </header>
    <content>
        <div class="cards">
            <div class="card">
                <image><%= image_tag 'des.png', class: "img" %></image>
                <h2>Biskit</h2>
                <p>
                    <%= link_to biskit_path do %>
                        <p>Allons-y <i class="fas fa-angle-right"></i></p>
                    <% end %>
                </p>
            </div>
            <div class="card">
                <image><%= image_tag 'never.png', class: "img" %></image>
                <h2>Je n'ai jamais...</h2>
                <p>
                    <%= link_to jenaijamais_path do %>
                        <p>Allons-y <i class="fas fa-angle-right"></i></p>
                    <% end %>
                </p>
            </div>
            <div class="card">
                <image><%= image_tag 'prefere.png', class: "img" %></image>
                <h2>Tu préfères ?</h2>
                <p>
                    <%= link_to prefereds_path do %>
                        <p>Allons-y <i class="fas fa-angle-right"></i></p>
                    <% end %>
                </p>
            </div>
        </div>
    </content>
    <div class="spotify">
        <iframe src="https://open.spotify.com/embed?uri=spotify:user:francoisrabanel:playlist:51sU5KhHJZI2TbzCuo9zw4" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
    </div>
    <footer>
        <div class="madeby">
            <p> Réalisé par <%= link_to 'FrançoisR', 'http://www.francoisrabanel.fr', target: '_blank' %></p>
        </div>
    </footer>
</div>

app/views/shared/_footer.html.erb
<footer>
</footer>